In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('/content/jogja.xlsx')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 32 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Address   1344 non-null   object
 1   Price     1344 non-null   object
 2   Info      1344 non-null   int64
 3   Info1     1344 non-null   object
 4   Info2     1344 non-null   object
 5   Info3     1344 non-null   object
 6   Info4     1341 non-null   object
 7   Info5     1341 non-null   object
 8   Field1    1344 non-null   object
 9   Field2    1344 non-null   int64
 10  Field3    1344 non-null   object
 11  Field4    1341 non-null   object
 12  Field7    1343 non-null   object
 13  Field8    1343 non-null   float64
 14  Field9    1343 non-null   object
 15  Field10   1343 non-null   float64
 16  Field11   836 non-null    object
 17  Field12   836 non-null    object
 18  Field13   93 non-null     object
 19  Field14   93 non-null     object
 20  Field15   42 non-null     object
 21  Field16   42 non-null     float64
 22  Field17   1343 non-null   object
 23  Field18   1343 non-null   object
 24  Field19   1341 non-null   object
 25  Field20   1341 non-null   object
 26  Field21   382 non-null    object
 27  Field22   382 non-null    object
 28  Field23   59 non-null     object
 29  Field24   59 non-null     object
 30  Field123  1111 non-null   object
 31  Text1     832 non-null    object
dtypes: float64(3), int64(2), object(27)
memory usage: 336.1+ KB

In [ ]:
df['Price'] = df['Price'].str.replace('Rp', '').str.replace('.', '').astype(int)

<ipython-input-435-661097e950d7>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Price'] = df['Price'].str.replace('Rp', '').str.replace('.', '').astype(int)

In [ ]:
df = df.rename(columns={"Price": "harga"})

In [ ]:
df = df.rename(columns={"Info": "kamar_tidur"})

In [ ]:
df = df.rename(columns={"Info2": "bangunan",'Info4':'lahan'})

In [ ]:
df = df.drop(['Info1','Info3','Info5'],axis=1)

In [ ]:
df = df.drop(['Field1','Field2','Field3','Field4'],axis=1)

In [ ]:
df.head()

,Address,harga,kamar_tidur,bangunan,lahan,Field7,Field8,Field9,Field10,Field11,...,Field17,Field18,Field19,Field20,Field21,Field22,Field23,Field24,Field123,Text1
0,Yogyakarta,980000000,2,66 m²,92 m²,Kamar tidur,2.0,Kamar mandi,2.0,NaN,...,Bangunan (m²),66,Lahan (m²),92,NaN,NaN,NaN,NaN,NaN,Fasilitas\n \n ...
1,"Jetis, Yogyakarta",1700000000,4,140 m²,500 m²,Kamar tidur,4.0,Kamar mandi,5.0,NaN,...,Bangunan (m²),140,Lahan (m²),500,NaN,NaN,NaN,NaN,SKU: HO65C1D656D2582ID,Fasilitas\n \n ...
2,"Mergangsan, Yogyakarta",4500000000,4,350 m²,230 m²,Lahan Parkir,2.0,Kamar tidur,4.0,Kamar mandi,...,Bangunan (m²),350,Lahan (m²),230,Tersedia sejak,24/10/23,NaN,NaN,SKU: HO65375C86074D8ID,Fasilitas\n \n ...
3,"Mantrijeron, Yogyakarta",1350000000,3,65 m²,90 m²,Dibangun (Tahun),2023.0,Lahan Parkir,1.0,Kamar tidur,...,Bangunan (m²),65,Lahan (m²),90,Jumlah Lantai,2,NaN,NaN,SKU: HO64F96956A63D9ID,Fasilitas\n \n ...
4,"Umbulharjo, Yogyakarta",1500000000,4,260 m²,151 m²,Kamar tidur,4.0,Kamar mandi,3.0,NaN,...,Bangunan (m²),260,Lahan (m²),151,NaN,NaN,NaN,NaN,SKU: HO6549F7EC283D9ID,Fasilitas\n \n ...

In [ ]:
df1 = df.copy()

In [ ]:
df1.head()

,Address,harga,kamar_tidur,bangunan,lahan,Field7,Field8,Field9,Field10,Field11,...,Field17,Field18,Field19,Field20,Field21,Field22,Field23,Field24,Field123,Text1
0,Yogyakarta,980000000,2,66 m²,92 m²,Kamar tidur,2.0,Kamar mandi,2.0,NaN,...,Bangunan (m²),66,Lahan (m²),92,NaN,NaN,NaN,NaN,NaN,Fasilitas\n \n ...
1,"Jetis, Yogyakarta",1700000000,4,140 m²,500 m²,Kamar tidur,4.0,Kamar mandi,5.0,NaN,...,Bangunan (m²),140,Lahan (m²),500,NaN,NaN,NaN,NaN,SKU: HO65C1D656D2582ID,Fasilitas\n \n ...
2,"Mergangsan, Yogyakarta",4500000000,4,350 m²,230 m²,Lahan Parkir,2.0,Kamar tidur,4.0,Kamar mandi,...,Bangunan (m²),350,Lahan (m²),230,Tersedia sejak,24/10/23,NaN,NaN,SKU: HO65375C86074D8ID,Fasilitas\n \n ...
3,"Mantrijeron, Yogyakarta",1350000000,3,65 m²,90 m²,Dibangun (Tahun),2023.0,Lahan Parkir,1.0,Kamar tidur,...,Bangunan (m²),65,Lahan (m²),90,Jumlah Lantai,2,NaN,NaN,SKU: HO64F96956A63D9ID,Fasilitas\n \n ...
4,"Umbulharjo, Yogyakarta",1500000000,4,260 m²,151 m²,Kamar tidur,4.0,Kamar mandi,3.0,NaN,...,Bangunan (m²),260,Lahan (m²),151,NaN,NaN,NaN,NaN,SKU: HO6549F7EC283D9ID,Fasilitas\n \n ...

In [ ]:
df1.head()

,Address,harga,kamar_tidur,bangunan,lahan,Field7,Field8,Field9,Field10,Field11,...,Field17,Field18,Field19,Field20,Field21,Field22,Field23,Field24,Field123,Text1
0,Yogyakarta,980000000,2,66 m²,92 m²,Kamar tidur,2.0,Kamar mandi,2.0,NaN,...,Bangunan (m²),66,Lahan (m²),92,NaN,NaN,NaN,NaN,NaN,Fasilitas\n \n ...
1,"Jetis, Yogyakarta",1700000000,4,140 m²,500 m²,Kamar tidur,4.0,Kamar mandi,5.0,NaN,...,Bangunan (m²),140,Lahan (m²),500,NaN,NaN,NaN,NaN,SKU: HO65C1D656D2582ID,Fasilitas\n \n ...
2,"Mergangsan, Yogyakarta",4500000000,4,350 m²,230 m²,Lahan Parkir,2.0,Kamar tidur,4.0,Kamar mandi,...,Bangunan (m²),350,Lahan (m²),230,Tersedia sejak,24/10/23,NaN,NaN,SKU: HO65375C86074D8ID,Fasilitas\n \n ...
3,"Mantrijeron, Yogyakarta",1350000000,3,65 m²,90 m²,Dibangun (Tahun),2023.0,Lahan Parkir,1.0,Kamar tidur,...,Bangunan (m²),65,Lahan (m²),90,Jumlah Lantai,2,NaN,NaN,SKU: HO64F96956A63D9ID,Fasilitas\n \n ...
4,"Umbulharjo, Yogyakarta",1500000000,4,260 m²,151 m²,Kamar tidur,4.0,Kamar mandi,3.0,NaN,...,Bangunan (m²),260,Lahan (m²),151,NaN,NaN,NaN,NaN,SKU: HO6549F7EC283D9ID,Fasilitas\n \n ...

In [ ]:
df1.head()

,Address,harga,kamar_tidur,bangunan,lahan,Field7,Field8,Field9,Field10,Field11,...,Field17,Field18,Field19,Field20,Field21,Field22,Field23,Field24,Field123,Text1
0,Yogyakarta,980000000,2,66 m²,92 m²,Kamar tidur,2.0,Kamar mandi,2.0,NaN,...,Bangunan (m²),66,Lahan (m²),92,NaN,NaN,NaN,NaN,NaN,Fasilitas\n \n ...
1,"Jetis, Yogyakarta",1700000000,4,140 m²,500 m²,Kamar tidur,4.0,Kamar mandi,5.0,NaN,...,Bangunan (m²),140,Lahan (m²),500,NaN,NaN,NaN,NaN,SKU: HO65C1D656D2582ID,Fasilitas\n \n ...
2,"Mergangsan, Yogyakarta",4500000000,4,350 m²,230 m²,Lahan Parkir,2.0,Kamar tidur,4.0,Kamar mandi,...,Bangunan (m²),350,Lahan (m²),230,Tersedia sejak,24/10/23,NaN,NaN,SKU: HO65375C86074D8ID,Fasilitas\n \n ...
3,"Mantrijeron, Yogyakarta",1350000000,3,65 m²,90 m²,Dibangun (Tahun),2023.0,Lahan Parkir,1.0,Kamar tidur,...,Bangunan (m²),65,Lahan (m²),90,Jumlah Lantai,2,NaN,NaN,SKU: HO64F96956A63D9ID,Fasilitas\n \n ...
4,"Umbulharjo, Yogyakarta",1500000000,4,260 m²,151 m²,Kamar tidur,4.0,Kamar mandi,3.0,NaN,...,Bangunan (m²),260,Lahan (m²),151,NaN,NaN,NaN,NaN,SKU: HO6549F7EC283D9ID,Fasilitas\n \n ...

In [ ]:
df_pivot1 = df1.pivot(columns='Field7', values='Field8')
df_pivot1.columns.name = None
df_pivot1.index.name = None

df_pivot2 = df1.pivot(columns='Field9', values='Field10')
df_pivot2.columns.name = None
df_pivot2.index.name = None

df_pivot3 = df1.pivot(columns='Field11', values='Field12')
df_pivot3.columns.name = None
df_pivot3.index.name = None

df_pivot4 = df1.pivot(columns='Field13', values='Field14')
df_pivot4.columns.name = None
df_pivot4.index.name = None

df_pivot5 = df1.pivot(columns='Field15', values='Field16')
df_pivot5.columns.name = None
df_pivot5.index.name = None

df_pivot6 = df1.pivot(columns='Field17', values='Field18')
df_pivot6.columns.name = None
df_pivot6.index.name = None

df_pivot7 = df1.pivot(columns='Field19', values='Field20')
df_pivot7.columns.name = None
df_pivot7.index.name = None

df_pivot8 = df1.pivot(columns='Field21', values='Field22')
df_pivot8.columns.name = None
df_pivot8.index.name = None

df_pivot9 = df1.pivot(columns='Field23', values='Field24')
df_pivot9.columns.name = None
df_pivot9.index.name = None

In [ ]:
df_hasil1 = df_pivot1.combine_first(df_pivot2)
df_hasil1.head()

,NaN,Bangunan (m²),Dibangun (Tahun),Kamar mandi,Kamar tidur,Lahan Parkir
0,NaN,NaN,NaN,2.0,2.0,NaN
1,NaN,NaN,NaN,5.0,4.0,NaN
2,NaN,NaN,NaN,NaN,4.0,2.0
3,NaN,NaN,2023.0,NaN,NaN,1.0
4,NaN,NaN,NaN,3.0,4.0,NaN

In [ ]:
df_hasil2 = df_pivot3.combine_first(df_pivot4)
df_hasil2.head()

,NaN,Bangunan (m²),Deposit / Kontrak,Fully furnished,Kamar mandi,Kamar tidur,Lahan (m²)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,4,NaN,NaN
3,NaN,NaN,NaN,NaN,3,3,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_result1 = df_hasil1.combine_first(df_hasil2)
df_result1.head()

,NaN,Bangunan (m²),Deposit / Kontrak,Dibangun (Tahun),Fully furnished,Kamar mandi,Kamar tidur,Lahan (m²),Lahan Parkir
0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,5.0,4.0,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,4,4.0,NaN,2.0
3,NaN,NaN,NaN,2023.0,NaN,3,3,NaN,1.0
4,NaN,NaN,NaN,NaN,NaN,3.0,4.0,NaN,NaN

In [ ]:
df_hasil3 = df_pivot5.combine_first(df_pivot6)
df_hasil2.head()

,NaN,Bangunan (m²),Deposit / Kontrak,Fully furnished,Kamar mandi,Kamar tidur,Lahan (m²)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,4,NaN,NaN
3,NaN,NaN,NaN,NaN,3,3,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_hasil4 = df_pivot7.combine_first(df_pivot8)
df_hasil4.head()

,NaN,Bangunan (m²),Jumlah Lantai,KM. Pembantu,KT. Pembantu,Kamar tidur,Kondisi harga,Lahan (m²),Tersedia sejak
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,230,24/10/23
3,NaN,NaN,2,NaN,NaN,NaN,NaN,90,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151,NaN

In [ ]:
df_result2 = df_hasil3.combine_first(df_hasil4)
df_result2.head()

,NaN,Bangunan (m²),Fully furnished,Jumlah Lantai,KM. Pembantu,KT. Pembantu,Kamar mandi,Kamar tidur,Kondisi harga,Lahan (m²),Tersedia sejak
0,NaN,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92,NaN
1,NaN,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500,NaN
2,NaN,350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,230,24/10/23
3,NaN,65,NaN,2,NaN,NaN,NaN,NaN,NaN,90,NaN
4,NaN,260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151,NaN

In [ ]:
df_result3 = df_result1.combine_first(df_result2)
df_result3.head()

,NaN,Bangunan (m²),Deposit / Kontrak,Dibangun (Tahun),Fully furnished,Jumlah Lantai,KM. Pembantu,KT. Pembantu,Kamar mandi,Kamar tidur,Kondisi harga,Lahan (m²),Lahan Parkir,Tersedia sejak
0,NaN,66,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,92,NaN,NaN
1,NaN,140,NaN,NaN,NaN,NaN,NaN,NaN,5.0,4.0,NaN,500,NaN,NaN
2,NaN,350,NaN,NaN,NaN,NaN,NaN,NaN,4,4.0,NaN,230,2.0,24/10/23
3,NaN,65,NaN,2023.0,NaN,2,NaN,NaN,3,3,NaN,90,1.0,NaN
4,NaN,260,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,NaN,151,NaN,NaN

In [ ]:
df_result_final = df_result3.combine_first(df_pivot9)
df_result_final.head()

,NaN,Bangunan (m²),Deposit / Kontrak,Dibangun (Tahun),Fully furnished,Jumlah Lantai,KM. Pembantu,KT. Pembantu,Kamar mandi,Kamar tidur,Kondisi harga,Lahan (m²),Lahan Parkir,Tersedia sejak
0,NaN,66,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,92,NaN,NaN
1,NaN,140,NaN,NaN,NaN,NaN,NaN,NaN,5.0,4.0,NaN,500,NaN,NaN
2,NaN,350,NaN,NaN,NaN,NaN,NaN,NaN,4,4.0,NaN,230,2.0,24/10/23
3,NaN,65,NaN,2023.0,NaN,2,NaN,NaN,3,3,NaN,90,1.0,NaN
4,NaN,260,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,NaN,151,NaN,NaN

In [ ]:
df1 = pd.concat([df1, df_result_final], axis=1)

In [ ]:
df1.head()

,Address,harga,kamar_tidur,bangunan,lahan,Field7,Field8,Field9,Field10,Field11,...,Fully furnished,Jumlah Lantai,KM. Pembantu,KT. Pembantu,Kamar mandi,Kamar tidur,Kondisi harga,Lahan (m²),Lahan Parkir,Tersedia sejak
0,Yogyakarta,980000000,2,66 m²,92 m²,Kamar tidur,2.0,Kamar mandi,2.0,NaN,...,NaN,NaN,NaN,NaN,2.0,2.0,NaN,92,NaN,NaN
1,"Jetis, Yogyakarta",1700000000,4,140 m²,500 m²,Kamar tidur,4.0,Kamar mandi,5.0,NaN,...,NaN,NaN,NaN,NaN,5.0,4.0,NaN,500,NaN,NaN
2,"Mergangsan, Yogyakarta",4500000000,4,350 m²,230 m²,Lahan Parkir,2.0,Kamar tidur,4.0,Kamar mandi,...,NaN,NaN,NaN,NaN,4,4.0,NaN,230,2.0,24/10/23
3,"Mantrijeron, Yogyakarta",1350000000,3,65 m²,90 m²,Dibangun (Tahun),2023.0,Lahan Parkir,1.0,Kamar tidur,...,NaN,2,NaN,NaN,3,3,NaN,90,1.0,NaN
4,"Umbulharjo, Yogyakarta",1500000000,4,260 m²,151 m²,Kamar tidur,4.0,Kamar mandi,3.0,NaN,...,NaN,NaN,NaN,NaN,3.0,4.0,NaN,151,NaN,NaN

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['sistem_alarm'] = df1['Text1'].str.contains('Sistem Alarm', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['sistem_alarm']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-457-a735f332471f>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['gym'] = df1['Text1'].str.contains('Gym', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['gym']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-458-d70264a741f0>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['Internet_broadband/Wifi'] = df1['Text1'].str.contains('Internet broadband/Wifi', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['Internet_broadband/Wifi']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-459-aae87db8fce9>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['tv_kabel'] = df1['Text1'].str.contains('TV kabel', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['tv_kabel']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-460-d069bb7cc041>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['pemanas_ruangan'] = df1['Text1'].str.contains('Pemanas ruangan', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['pemanas_ruangan']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-461-524f85eba4e8>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['ac'] = df1['Text1'].str.contains('Pendingin ruangan (AC)', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['ac']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-462-2eb9e70bea4e>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()
<ipython-input-462-2eb9e70bea4e>:8: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df1['ac'] = df1['Text1'].str.contains('Pendingin ruangan (AC)', case=False, na=False).map({True: 'Y', False: 'N'})

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['air_panas'] = df1['Text1'].str.contains('Air Panas', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['air_panas']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-463-9b66d8f369a5>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['telepon'] = df1['Text1'].str.contains('Telepon', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['telepon']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-464-23fbb1a40c7c>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['tv'] = df1['Text1'].str.contains('Televis', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['tv']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-465-4b5efb07df88>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['kitchen_set'] = df1['Text1'].str.contains('Kitchen set', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['kitchen_set']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-466-bc47f9c4c7f2>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['garasi'] = df1['Text1'].str.contains('Garasi', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['garasi']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-467-63d9793609ed>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['secure_parking'] = df1['Text1'].str.contains('Secure parking', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['secure_parking']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-468-67900056d927>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['kolam_renang'] = df1['Text1'].str.contains('Kolam renang', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['kolam_renang']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-469-1b223739de87>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['lapangan_tenis'] = df1['Text1'].str.contains('Lapangan tenis', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['lapangan_tenis']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-470-1d6bd5296a64>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['balkon'] = df1['Text1'].str.contains('Balkon', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['balkon']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-471-05f2cd83a09e>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['dek'] = df1['Text1'].str.contains('Dek', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['dek']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-472-6d79e448ea5e>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['halaman_terbuka'] = df1['Text1'].str.contains('Halaman terbuka', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['halaman_terbuka']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-473-9ec0e4d629cb>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['area_hiburan_outdoor'] = df1['Text1'].str.contains('Area hiburan outdoor', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['area_hiburan_outdoor']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-474-f30294c87763>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['pagar_penuh'] = df1['Text1'].str.contains('Pagar penuh', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['pagar_penuh']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-475-ac5cd5cc3581>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['taman'] = df1['Text1'].str.contains('Taman', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['taman']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-476-ee742f99f47c>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['keamanan_24_jam'] = df1['Text1'].str.contains('Keamanan 24 Jam', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['keamanan_24_jam']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-477-bbf87f818635>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
# Mengganti nilai NaN dengan string kosong
df1['Text1'] = df1['Text1'].fillna('')

# Membersihkan dan memisahkan teks menjadi beberapa baris
df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

# Membuat kolom baru 'Kitchen_set' dan mengisi nilai Y jika 'Kitchen set' muncul
df1['taman_bermain_anak'] = df1['Text1'].str.contains('Taman bermain anak', case=False, na=False).map({True: 'Y', False: 'N'})

# Menggabungkan hasil dengan dataframe asli
df1 = pd.concat([df1, df1['taman_bermain_anak']], axis=1)

# Menghapus kolom ganda jika ada
df1 = df1.loc[:, ~df1.columns.duplicated()]

<ipython-input-478-af8c76a52a9c>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Text1'] = df1['Text1'].str.replace(r'\n', '').str.strip()

In [ ]:
df1 = df1.drop(['Text1'],axis=1)

In [ ]:
df1['bangunan'] = df1['bangunan'].str.replace('m²', '')
df1['lahan'] = df1['lahan'].str.replace('m²', '')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 60 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Address                  1344 non-null   object
 1   harga                    1344 non-null   int64
 2   kamar_tidur              1344 non-null   int64
 3   bangunan                 1344 non-null   object
 4   lahan                    1341 non-null   object
 5   Field7                   1343 non-null   object
 6   Field8                   1343 non-null   float64
 7   Field9                   1343 non-null   object
 8   Field10                  1343 non-null   float64
 9   Field11                  836 non-null    object
 10  Field12                  836 non-null    object
 11  Field13                  93 non-null     object
 12  Field14                  93 non-null     object
 13  Field15                  42 non-null     object
 14  Field16                  42 non-null     float64
 15  Field17                  1343 non-null   object
 16  Field18                  1343 non-null   object
 17  Field19                  1341 non-null   object
 18  Field20                  1341 non-null   object
 19  Field21                  382 non-null    object
 20  Field22                  382 non-null    object
 21  Field23                  59 non-null     object
 22  Field24                  59 non-null     object
 23  Field123                 1111 non-null   object
 24  nan                      0 non-null      float64
 25  Bangunan (m²)            1342 non-null   object
 26  Deposit / Kontrak        2 non-null      object
 27  Dibangun (Tahun)         64 non-null     float64
 28  Fully furnished          42 non-null     object
 29  Jumlah Lantai            277 non-null    object
 30  KM. Pembantu             13 non-null     object
 31  KT. Pembantu             22 non-null     object
 32  Kamar mandi              1343 non-null   object
 33  Kamar tidur              1343 non-null   object
 34  Kondisi harga            45 non-null     object
 35  Lahan (m²)               1340 non-null   object
 36  Lahan Parkir             597 non-null    float64
 37  Tersedia sejak           352 non-null    object
 38  sistem_alarm             1344 non-null   object
 39  gym                      1344 non-null   object
 40  Internet_broadband/Wifi  1344 non-null   object
 41  tv_kabel                 1344 non-null   object
 42  pemanas_ruangan          1344 non-null   object
 43  ac                       1344 non-null   object
 44  air_panas                1344 non-null   object
 45  telepon                  1344 non-null   object
 46  tv                       1344 non-null   object
 47  kitchen_set              1344 non-null   object
 48  garasi                   1344 non-null   object
 49  secure_parking           1344 non-null   object
 50  kolam_renang             1344 non-null   object
 51  lapangan_tenis           1344 non-null   object
 52  balkon                   1344 non-null   object
 53  dek                      1344 non-null   object
 54  halaman_terbuka          1344 non-null   object
 55  area_hiburan_outdoor     1344 non-null   object
 56  pagar_penuh              1344 non-null   object
 57  taman                    1344 non-null   object
 58  keamanan_24_jam          1344 non-null   object
 59  taman_bermain_anak       1344 non-null   object
dtypes: float64(6), int64(2), object(52)
memory usage: 630.1+ KB

In [ ]:
df1.head()

,Address,harga,kamar_tidur,bangunan,lahan,Field7,Field8,Field9,Field10,Field11,...,kolam_renang,lapangan_tenis,balkon,dek,halaman_terbuka,area_hiburan_outdoor,pagar_penuh,taman,keamanan_24_jam,taman_bermain_anak
0,Yogyakarta,980000000,2,66,92,Kamar tidur,2.0,Kamar mandi,2.0,NaN,...,N,N,N,N,N,N,N,Y,N,N
1,"Jetis, Yogyakarta",1700000000,4,140,500,Kamar tidur,4.0,Kamar mandi,5.0,NaN,...,N,N,N,N,N,N,N,Y,Y,Y
2,"Mergangsan, Yogyakarta",4500000000,4,350,230,Lahan Parkir,2.0,Kamar tidur,4.0,Kamar mandi,...,Y,N,Y,Y,Y,Y,Y,Y,Y,Y
3,"Mantrijeron, Yogyakarta",1350000000,3,65,90,Dibangun (Tahun),2023.0,Lahan Parkir,1.0,Kamar tidur,...,N,N,Y,Y,Y,N,Y,Y,Y,N
4,"Umbulharjo, Yogyakarta",1500000000,4,260,151,Kamar tidur,4.0,Kamar mandi,3.0,NaN,...,N,N,N,N,N,N,N,Y,N,N

In [ ]:
df1 = df1.drop(['Field7','Field8', 'Field9', 'Field10','Field11','Field12','Field13','Field14','Field15','Field16','Field17','Field18','Field19','Field20','Field21','Field22','Field23','Field24'],axis=1)

In [ ]:
df1 = df1.rename(columns={"Field123": "SKU"})

In [ ]:
df1.info()

In [ ]:
df1.head()

,Address,harga,kamar_tidur,bangunan,lahan,SKU,NaN,Bangunan (m²),Deposit / Kontrak,Dibangun (Tahun),...,secure_parking,kolam_renang,lapangan_tenis,balkon,dek,halaman_terbuka,area_hiburan_outdoor,pagar_penuh,taman,taman_bermain_anak
0,Yogyakarta,980000000,2,66,92,NaN,NaN,66,NaN,NaN,...,N,N,N,N,N,N,N,N,Y,N
1,"Jetis, Yogyakarta",1700000000,4,140,500,SKU: HO65C1D656D2582ID,NaN,140,NaN,NaN,...,Y,N,N,N,N,N,N,N,Y,Y
2,"Mergangsan, Yogyakarta",4500000000,4,350,230,SKU: HO65375C86074D8ID,NaN,350,NaN,NaN,...,Y,Y,N,Y,Y,Y,Y,Y,Y,Y
3,"Mantrijeron, Yogyakarta",1350000000,3,65,90,SKU: HO64F96956A63D9ID,NaN,65,NaN,2023.0,...,Y,N,N,Y,Y,Y,N,Y,Y,N
4,"Umbulharjo, Yogyakarta",1500000000,4,260,151,SKU: HO6549F7EC283D9ID,NaN,260,NaN,NaN,...,N,N,N,N,N,N,N,N,Y,N

In [ ]:
df1.to_csv('jogja_.csv',index=False)